<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.litterat.test.core.SealedAbstractRecordTest" tests="4" skipped="0" failures="1" errors="0" timestamp="2025-01-02T01:06:28" hostname="Davids-MacBook-Air-2.local" time="0.014">
  <properties/>
  <testcase name="testMapToObjectException()" classname="io.litterat.test.core.SealedAbstractRecordTest" time="0.007">
    <failure message="org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;io.litterat.core.TypeException&gt; but was: &lt;io.litterat.bind.DataBindException&gt;" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;io.litterat.core.TypeException&gt; but was: &lt;io.litterat.bind.DataBindException&gt;
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at app/io.litterat.test.core/io.litterat.test.core.SealedAbstractRecordTest.testMapToObjectException(SealedAbstractRecordTest.java:137)
	at java.base@23.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@23.0.1/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base@23.0.1/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: io.litterat.bind.DataBindException: Failed to convert Map to class io.litterat.test.core.data.SealedAbstractRecord$SealedShapeList.
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:204)
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:124)
	at app/io.litterat.test.core/io.litterat.test.core.SealedAbstractRecordTest.lambda$testMapToObjectException$0(SealedAbstractRecordTest.java:138)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more
Caused by: io.litterat.bind.DataBindException: Failed to convert Map to interface java.util.List.
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:204)
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:154)
	... 9 more
Caused by: io.litterat.bind.DataBindException: Failed to convert Map to class io.litterat.test.core.data.SealedAbstractRecord$SealedShape.
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:204)
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:173)
	... 10 more
Caused by: java.lang.ClassNotFoundException: io.litterat.test.bind.union.SealedInterfaceUnionRectangle
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:462)
	at java.base/java.lang.Class.forName(Class.java:453)
	at io.litterat.bind/io.litterat.bind.mapper.MapMapper.toObject(MapMapper.java:187)
	... 11 more
</failure>
  </testcase>
  <testcase name="testToArray()" classname="io.litterat.test.core.SealedAbstractRecordTest" time="0.003"/>
  <testcase name="testToMap()" classname="io.litterat.test.core.SealedAbstractRecordTest" time="0.001"/>
  <testcase name="checkDescriptor()" classname="io.litterat.test.core.SealedAbstractRecordTest" time="0.001"/>
  <system-out><![CDATA[[{x=1, y=2, type=io.litterat.test.core.data.SealedAbstractRecord$RecordPoint}, {x=3, y=4, radius=5, type=io.litterat.test.core.data.SealedAbstractRecord$RecordCircle}]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
